lib/jsdoc/opts/args.js, lib/jsdoc/schema.js, lib/jsdoc/tag/dictionary/definitions.js, lib/jsdoc/util/templateHelper.js, test/fixtures/accesstag.js, test/specs/jsdoc/opts/args.js, test/specs/jsdoc/util/templateHelper.js, test/specs/tags/accesstag.js
The idea behind adding the "access" parameter is to generate documentation by only displaying objects that match the parameter settings. The parameter can have the values `public`, `protected`, `undefined` or `private` and multiple access parameters may be specified.
E.g. `--access public --access protected` will exclude undefined and private objects from the documentation.
To facilitate this a split between 'access undefined' and 'access public' is being introduced, which allows detection later on in the process. Tests have been expanded to include new test cases.
(This is the squashed version of pull request jsdoc3/jsdoc#829)
=> Adding access parameter

lib/jsdoc/util/markdown.js, test/specs/jsdoc/util/markdown.js
This fixes https://github.com/jsdoc3/jsdoc/pull/529
=> Add support for a `markdown.hardwrap` config property

templates/default/tmpl/container.tmpl
Prevents unnecessary space between ancestors and object name.
Could also just use: 
`25 | `` `` `` ``<span class="ancestors"><?js= doc.ancestors.join('') ?></span><?js `
=> Remove whitespace from around object name

README.md
The shields.io image kept not showing up:
=> Direct link to Travis build image

lib/jsdoc/util/markdown.js
This pull request gives the user a configuration so that he can choose to let the markdown parser add an anchor in the headings. This feature is very useful if you want to point directly to specific parts of a tutorial generated with markdown (that's my current use case).
To use the feature : set the attribute anchorInHeadings in the markdown part of the configuration file. The default is set to false.
```
{
"markdown" : {
"idInHeadings" : true
}
}
```
I would have added some tests, but there seems to be none existing so far for the markdown. If it is necessary, could you give a hand in making them?
Cheers.
=> Make the markdown parser able to generate anchors for headings

templates/default/publish.js
Currently, only the names of the symbols themselves are shown in the navigation. However this is confusing and results in ambiguous names in larger projects. So I'd like to add an option to show the full namepath instead.
=> Added option to use longnames in navigation to default template

lib/jsdoc/src/walker.js
This fixes an error I encountered when trying to run jsdoc on a file with a JSXMemberExpression (something like this: `<foo.bar>hello</foo.bar>`).
=> Fix typo in JSXMemberExpresson walker

cli.js, jsdoc.js, lib/jsdoc/path.js, lib/jsdoc/src/parser.js, lib/jsdoc/tag/dictionary/definitions.js, node/fs.js, plugins/sourcetag.js, test/lib/jasmine.js, test/spec-collection.js
This eliminates the following when running `gulp lint`:
> error  Keyword "catch" must be followed by whitespace
Closes #1083
=> Clean up space-after-keywords lint violations

templates/haruki/publish.js
When a `@param` has falsy value it's not displayed in JSON result:
```js
/**
* Float number in specified range.
* @param {number} [min=0] - Minimum number in the range.
* @param {number} [max=10] - Maximum number in the range.
* @returns {Number}
*/
```
Result:
```json
...
{
"name": "min",
"type": "number",
"description": "Minimum number in the range.",
"default": "",
"optional": true,
"nullable": ""
}
...
```
=> fix displaying of falsy default values in haruki template

cli.js
This is a quick fix for truncated output in Node 4 by only calling
`process.exit` for errors.
Closes #1070
=> Prevent output from being cut off in Node 4

lib/jsdoc/util/markdown.js
Fixes #1035 
See issue #1035 for a full description of the problem, cliff notes here though:
If a namepath has special characters in it (e.g. periods, hash symbol, etc), you need to quote the name that contains the special character (see http://usejsdoc.org/about-namepaths.html, section "Namepaths of objects with special characters in the name"). A short example is:
```
/** @namespace */
var chat = {
/**
* Refer to this by {@link chat."#channel"}.
* @namespace
*/
"#channel": {
}
}
```
The `marked` parser for the markdown plugin converts the `"` character into the html entity `&quot;`, which breaks namepaths (and produces my specific issue of links not working in the generated doc).
This PR solves that by creating an `unencodeQuotes(...)` method, that grabs the `{@ ... }` tags, and …
=> Fix markdown breaking namepaths w/special chars

templates/silent/README.md, templates/silent/publish.js
This commit creates a template named `silent` which outputs nothing at all.  As discussed in the `README.md`, this can be useful when running JSDoc as a linter to check for syntax errors or unknown tags.  It may also be useful for testing or benchmarking.
The same effect can be achieved using the haruki template and redirecting the output to `/dev/null`, but that has a few downsides:
* It is non-obvious.
* It is difficult to do in scripts which must run in both `bash` and `cmd.exe` (like npm scripts).
* It is slower due to the unnecessary formatting work and output syscalls.
This template could be distributed as a third-party template, but given the tiny code size, broad applicability, and potential usefulness for tests, I thought it might make sense to include it officially.  But, if you …
=> Create silent template

lib/jsdoc/tag/validator.js, test/specs/jsdoc/tag/validator.js
This PR adds support for specifying an Array of tags which are unknown to JSDoc, but allowed without error.  It provides a more granular way to disable such errors while retaining the benefits of catching errant tags (e.g. typos).
The intended use case is catching errant tags when using additional tools which support tags not recognized by JSDoc (e.g. Closure Compiler and the tags discussed in #605).
It also removes a block of dead code relating to `allowUnknownTags` which I noticed while creating the PR.  The removal is made in a separate commit to ease review.
Thanks for considering,
Kevin
=> Support an Array of tags titles in allowUnknownTags

.eslintrc, gulpfile.js, lib/jsdoc/fs.js, lib/jsdoc/opts/args.js, lib/jsdoc/src/astnode.js, lib/jsdoc/src/handlers.js, lib/jsdoc/src/parser.js, lib/jsdoc/src/visitor.js, lib/jsdoc/tag/dictionary/definitions.js, lib/jsdoc/util/markdown.js, package.json, plugins/sourcetag.js, templates/default/publish.js, templates/haruki/publish.js, test/jasmine-jsdoc.js, test/spec-collection.js, test/specs/jsdoc/util/templateHelper.js
Except `espree` because I don't know how to fix the breaking changes.
Started this to scratch the itch that `npm` warned that wrench was deprecated in favor of `fs-extra` but ended up going through all dependencies.
=> Upgrade dependencies

cli.js, lib/jsdoc/path.js, test/specs/jsdoc/path.js
The issue has been reported in #1081 (and its duplicates #1097 and #1114). A fix was initially proposed by @GerHobbelt and merged in Dec 2015 (6be9dac616549ce226e4c0064876c7cb3b64fe25), only to be reverted in Sep 2016 (see [comment] and #1259 for why). Indeed, the initially proposed fix was in some ways a hack, because it made assumptions that are in fact not met in common and important situations.
This solution takes a different route. In essence, it considers the current behavior of `jsdoc/path.getResourcePath()` broken, because it did not differentiate between filepath specifications given relative to where packages are installed, and those relative to the current or module directory (i.e., starting with `./` or `../`). This is in sharp contrast to how module identifiers are resolved …
=> Fixes directory name clashes with JSDoc plugin and template loading

templates/default/static/styles/jsdoc-default.css
There is small bug in default style, wide images can screw up the layout.
`max-width: 100%;` solved the problem : )
=> Added css fix for wide images.

cli.js
| Q                | A
| ---------------- | ---
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Deprecations?    | no
| Tests added?     | no
| Fixed issues     | n/a
| License          | Apache-2.0
Since process.exit() is an imperative that exits immediately, pending
contents written to STDOUT is lost, if STDOUT is connected to a pipe
(as it is, for example, when used by sphinx-js to generate automatic
class descriptions).
The deferred exit in this commit allows STDOUT to flush its full
contents, before the jsdoc process exits with the designated exit code.
Please see
https://github.com/nodejs/node-v0.x-archive/issues/3737#issuecomment-19156072
for details.
=> Deferred process.exit() to allow STDOUT pipe to flush

lib/jsdoc/fs.js, package.json
`lib/jsdoc/fs.js` always prefers native implementations over its overrides. With node v8.5 implementing `copyFile` and `copyFileSync` natively with a different API, building docs broke.
I've made it so overrides can now easily be preferred by adding them to the `alwaysOverride` object.
Fixes #1438.
=> Prefer copyFileSync from here over native

README.md
| Q                | A
| ---------------- | ---
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Deprecations?    | no
| Tests added?     | no
| Fixed issues     | 
| License          | Apache-2.0
This PR adds a **link** in the `README.md` file to a new [GitHub Action](https://github.com/features/actions) that I have created.
The Action is called `jsdoc-action` and is available at https://github.com/andstor/jsdoc-action.
It's also published at the GitHub marketplace at https://github.com/marketplace/actions/jsdoc-action.
It is a JavaScript GitHub Action to generate JavaScript documentation with JSDoc. The action can also easily be combined with other deployment actions, in order to automatically publish the generated documentation to for example GitHub Pages. …
=> Add link to jsdoc-action GitHub Action in the README file

README.md
This makes it easier to access these files by simply clicking on the
relevant name in the README.md file, rather than having to scroll up to
the file list and manually finding the relevant file being discussed.
=> Add links to CONTRIBUTING.md and LICENSE [skip ci]

package-lock.json, package.json
| Q                | A                                                                |
| ---------------- | ---------------------------------------------------------------- |
| Bug fix?         | yes                                                           |
| New feature?     | no                                                           |
| Breaking change? | no                                                           |
| Deprecations?    | no                                                           |
| Tests added?     | no                                                           |
| Fixed issues     | #2000 |
| License          | Apache-2.0                                                       |
As described in #2000, pulling `klaw` v4 makes `jsdoc` require Node.js v14. …
=> fix(deps): rollback klaw to 3.x
